import { useState, useEffect, useCallback, useRef } from "react";
const PAIRS_API = "https://api.dexscreener.com/latest/dex/search?q=solana";
function timeAgo(ts){if(!ts)return"?";const d=Math.floor((Date.now()-ts)/1000);if(d<60)return`${d}s`;if(d<3600)return`${Math.floor(d/60)}m`;if(d<86400)return`${Math.floor(d/3600)}h`;return`${Math.floor(d/86400)}d`;}
function fmt(n){if(!n&&n!==0)return"—";if(n>=1e6)return`$${(n/1e6).toFixed(1)}M`;if(n>=1000)return`$${(n/1000).toFixed(1)}K`;return`$${n.toFixed(0)}`;}
function calcScore(c){let s=0;const v=c.volume24h||0,mc=c.fdv||0,ch=parseFloat(c.change6h)||0,t=c.txns24h||0;if(v>500000)s+=25;else if(v>100000)s+=18;else if(v>10000)s+=10;else s+=3;if(ch>200)s+=30;else if(ch>50)s+=20;else if(ch>10)s+=10;else if(ch<0)s-=10;if(mc>0&&v>0){const r=v/mc;if(r>2)s+=20;else if(r>0.5)s+=12;else s+=4;}if(t>500)s+=15;else if(t>100)s+=10;else s+=3;if(c.isNew)s+=8;return Math.max(0,Math.min(99,s));}
function ScoreBar({score}){const color=score>=75?"#00ff88":score>=45?"#ffcc00":"#ff4455";return(<div style={{display:"flex",alignItems:"center",gap:8}}><div style={{flex:1,height:4,background:"#1a1a2e",borderRadius:2,overflow:"hidden"}}><div style={{width:`${score}%`,height:"100%",background:color,borderRadius:2}}/></div><span style={{fontSize:12,color,fontWeight:700,minWidth:26,fontFamily:"monospace"}}>{score}</span></div>);}
function StatCard({label,value,sub,accent}){return(<div style={{background:"rgba(255,255,255,0.03)",border:"1px solid rgba(255,255,255,0.07)",borderRadius:14,padding:"16px 20px"}}><div style={{fontSize:11,color:"#555",textTransform:"uppercase",letterSpacing:1,marginBottom:6}}>{label}</div><div style={{fontSize:22,fontWeight:900,color:accent||"#fff"}}>{value}</div>{sub&&<div style={{fontSize:11,color:"#444",marginTop:2}}>{sub}</div>}</div>);}
function CoinRow({coin,index}){const isPos=(parseFloat(coin.change6h)||0)>=0;const ch=coin.change6h!=null?`${isPos?"+":""}${parseFloat(coin.change6h).toFixed(0)}%`:"—";return(<div style={{display:"grid",gridTemplateColumns:"2fr 1fr 1fr 1fr 1.2fr",alignItems:"center",padding:"13px 20px",borderBottom:"1px solid rgba(255,255,255,0.04)",cursor:"pointer"}} onClick={()=>coin.url&&window.open(coin.url,"_blank")}><div style={{display:"flex",alignItems:"center",gap:10}}><div style={{width:36,height:36,borderRadius:10,flexShrink:0,background:`hsl(${(coin.symbol?.charCodeAt(0)||65)*47%360},65%,40%)`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:13,fontWeight:900,color:"#fff"}}>{(coin.symbol||"?")[0]}</div><div><div style={{display:"flex",alignItems:"center",gap:5}}><span style={{fontWeight:700,fontSize:14,color:"#fff"}}>{coin.name?.length>14?coin.name.slice(0,14)+"…":coin.name}</span>{coin.score>=75&&<span style={{fontSize:9,background:"rgba(255,80,50,0.2)",color:"#ff6644",border:"1px solid rgba(255,80,50,0.3)",borderRadius:4,padding:"1px 5px",fontWeight:700}}>HOT</span>}{coin.isNew&&<span style={{fontSize:9,background:"rgba(0,255,136,0.15)",color:"#00ff88",border:"1px solid rgba(0,255,136,0.3)",borderRadius:4,padding:"1px 5px",fontWeight:700}}>NEW</span>}</div><span style={{fontSize:11,color:"#555"}}>${coin.symbol} · {coin.age}</span></div></div><div style={{textAlign:"right"}}><div style={{fontSize:13,color:"#ccc"}}>{fmt(coin.fdv)}</div><div style={{fontSize:11,color:"#444"}}>mkt cap</div></div><div style={{textAlign:"right"}}><span style={{fontSize:13,fontWeight:700,color:isPos?"#00ff88":"#ff4455"}}>{ch}</span><div style={{fontSize:11,color:"#444"}}>6h</div></div><div style={{textAlign:"right"}}><div style={{fontSize:13,color:"#aaa"}}>{fmt(coin.volume24h)}</div><div style={{fontSize:11,color:"#444"}}>vol</div></div><div style={{paddingLeft:10}}><ScoreBar score={coin.score}/></div></div>);}
const FILTERS=["All","Hot 🔥","New ⚡","High Score"];
export default function App(){const[coins,setCoins]=useState([]);const[filter,setFilter]=useState("All");const[loading,setLoading]=useState(true);const[error,setError]=useState(null);const[alert,setAlert]=useState(null);const prev=useRef(new Set());
const fetch2=useCallback(async()=>{try{const r=await fetch(PAIRS_API);if(!r.ok)throw new Error();const d=await r.json();const now=Date.now();const mapped=(d.pairs||[]).filter(p=>p.chainId==="solana"&&p.baseToken?.symbol).slice(0,40).map(p=>{const cr=p.pairCreatedAt||null;const isNew=cr?(now-cr)<600000:false;const c={id:p.pairAddress,name:p.baseToken.name,symbol:p.baseToken.symbol,age:timeAgo(cr),fdv:p.fdv||p.marketCap||0,change6h:p.priceChange?.h6??p.priceChange?.h1??null,volume24h:p.volume?.h24||0,txns24h:(p.txns?.h24?.buys||0)+(p.txns?.h24?.sells||0),url:p.url,isNew};c.score=calcScore(c);return c;});if(prev.current.size>0){const n=mapped.filter(c=>!prev.current.has(c.id)&&c.isNew);if(n.length>0){setAlert(n[0]);setTimeout(()=>setAlert(null),4000);}}prev.current=new Set(mapped.map(c=>c.id));setCoins(mapped);setError(null);}catch{setError("Erro ao buscar dados.");}finally{setLoading(false);};},[]);
useEffect(()=>{fetch2();const i=setInterval(fetch2,20000);return()=>clearInterval(i);},[fetch2]);
const filtered=coins.filter(c=>{if(filter==="Hot 🔥")return c.score>=70;if(filter==="New ⚡")return c.isNew;if(filter==="High Score")return c.score>=75;return true;});
const hot=coins.filter(c=>c.score>=70).length;const avg=coins.length?Math.round(coins.reduce((a,c)=>a+c.score,0)/coins.length):0;
return(<><style>{`@import url('https://fonts.googleapis.com/css2?family=Syne:wght@700;900&family=Space+Mono&display=swap');*{box-sizing:border-box;margin:0;padding:0;}body{background:#080810;}@keyframes spin{to{transform:rotate(360deg)}}@keyframes pulse{0%,100%{opacity:1}50%{opacity:0.3}}@keyframes slideIn{from{transform:translateX(120%);opacity:0}to{transform:translateX(0);opacity:1}}`}</style>
<div style={{minHeight:"100vh",background:"#080810",color:"#fff",fontFamily:"'Syne',sans-serif"}}>
<div style={{maxWidth:920,margin:"0 auto",padding:"0 16px 60px"}}>
<div style={{padding:"28px 0 22px",borderBottom:"1px solid rgba(255,255,255,0.06)",display:"flex",alignItems:"center",justifyContent:"space-between",flexWrap:"wrap",gap:12}}>
<div><div style={{display:"flex",alignItems:"center",gap:10}}><div style={{width:34,height:34,borderRadius:9,background:"linear-gradient(135deg,#00ff88,#00ccff)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:17}}>⚡</div><h1 style={{fontSize:27,fontWeight:900,letterSpacing:-0.5}}>Pump<span style={{color:"#00ff88"}}>Radar</span></h1></div><p style={{fontSize:11,color:"#444",marginTop:4}}>solana meme coins · dados reais · atualiza a cada 20s</p></div>
<div style={{display:"flex",alignItems:"center",gap:7}}><div style={{width:8,height:8,borderRadius:"50%",background:error?"#ff4455":"#00ff88",animation:"pulse 1.5s infinite"}}/><span style={{fontSize:12,color:error?"#ff4455":"#00ff88"}}>{error?"ERRO":"AO VIVO"}</span></div></div>
<div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:12,margin:"22px 0"}}><StatCard label="Coins" value={loading?"…":coins.length} sub="rede Solana"/><StatCard label="Hot 🔥" value={loading?"…":hot} sub="score ≥ 70" accent="#00ff88"/><StatCard label="Score Médio" value={loading?"…":avg} accent="#ffcc00"/></div>
<div style={{display:"flex",gap:8,marginBottom:14,flexWrap:"wrap"}}>{FILTERS.map(f=><button key={f} onClick={()=>setFilter(f)} style={{padding:"7px 16px",borderRadius:8,border:"none",cursor:"pointer",fontFamily:"'Syne',sans-serif",fontWeight:700,fontSize:13,background:filter===f?"#00ff88":"rgba(255,255,255,0.05)",color:filter===f?"#080810":"#777"}}>{f}</button>)}</div>
<div style={{background:"rgba(255,255,255,0.02)",border:"1px solid rgba(255,255,255,0.07)",borderRadius:16,overflow:"hidden"}}>
<div style={{display:"grid",gridTemplateColumns:"2fr 1fr 1fr 1fr 1.2fr",padding:"10px 20px",borderBottom:"1px solid rgba(255,255,255,0.06)"}}>{["Coin","Mkt Cap","Var 6h","Vol 24h","AI Score"].map((h,i)=><div key={h} style={{fontSize:10,color:"#444",textTransform:"uppercase",letterSpacing:1,textAlign:i===0||i===4?"left":"right",paddingLeft:i===4?10:0}}>{h}</div>)}</div>
{loading&&<div style={{padding:60,textAlign:"center"}}><div style={{width:28,height:28,border:"3px solid rgba(0,255,136,0.2)",borderTopColor:"#00ff88",borderRadius:"50%",animation:"spin 0.8s linear infinite",margin:"0 auto 14px"}}/><div style={{color:"#444",fontSize:12}}>Buscando coins na Solana…</div></div>}
{!loading&&filtered.length===0&&<div style={{padding:40,textAlign:"center",color:"#444"}}>Nenhuma coin encontrada</div>}
{!loading&&filtered.map((c,i)=><CoinRow key={c.id} coin={c} index={i}/>)}
</div></div>
{alert&&<div style={{position:"fixed",bottom:24,right:24,zIndex:100,background:"#0d0d1c",border:"1px solid rgba(0,255,136,0.35)",borderRadius:14,padding:"14px 18px",maxWidth:270,animation:"slideIn 0.3s ease"}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:5}}><div style={{width:7,height:7,borderRadius:"50%",background:"#00ff88",animation:"pulse 1s infinite"}}/><span style={{fontSize:10,color:"#00ff88",fontWeight:700}}>NOVA COIN</span></div><div style={{fontSize:16,fontWeight:900,color:"#fff"}}>{alert.name}</div><div style={{fontSize:12,color:"#555",marginTop:2}}>{fmt(alert.fdv)} · score {alert.score}</div></div>}
</div></>);}
